version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data: